homeassistant:
  # Name of the location where Home Assistant is running
  name: Casa
  # Location required to calculate the time the sun rises and sets
  latitude: -13.00
  longitude: -55.00
  # Impacts weather/sunrise data
  elevation: 48
  #Temperature Units
  temperature_unit: C
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Cuiaba
  # Customized Names
  customize: !include customized.yaml

http:
  # Uncomment this to add a password (recommended!)
  api_password: password

mqtt:
  username: homeassistant
  password: password
  keepalive: 60

sensor: !include sensor.yaml

input_select: !include input_select.yaml

switch: !include switch.yaml

#automation: !include automation.yaml

group:  !include group.yaml


########################
#                      #
#       ENABLES        #
#                      #   
########################

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

logger:

frontend: