- platform: mqtt
  name: 'Luminosidade da Sala'
  state_topic: 'home-assistant/SensorDaSala/luminosidade'
  unit_of_measurement: 'cd'

- platform: mqtt
  name: 'Temperatura Interna da Sala'
  state_topic: "home-assistant/SensorDaSala/temperatura"
  unit_of_measurement: '°C'

- platform: mqtt
  name: 'Umidade Interna Da Sala'
  state_topic: "home-assistant/SensorDaSala/umidade"
  unit_of_measurement: '%'

- platform: time_date
  display_options:
    - 'date'
    - 'time'

- platform: forecast
  name: 'Forecast'
  api_key: #secret
  monitored_conditions:
   # - summary
   # - iconwater-percent
   # - nearest_storm_distance
   # - nearest_storm_bearing
   # - precip_type
    - precip_intensity
    - precip_probability
    - temperature
    - apparent_temperature
   # - dew_point
   # - wind_speed
   # - wind_bearing
   # - cloud_cover
    - humidity
   # - pressure
   # - visibility
   # - ozone
   # - minutely_summary
   # - hourly_summary
   # - daily_summary
    - temperature_max
    - temperature_min
    - apparent_temperature_max
    - apparent_temperature_min
   # - precip_intensity_max